### PR TITLE
issues2/to a

### PR DESCRIPTION
**Pull request by tashirosota**

### CODE REVIEW

**Comment by tashirosota** [comment]
https://github.com/tashirosota/ex-r_enum/issues/10

**Comment by tashirosota** [comment]
@mnishiguchi 
In addition, the return value when doing something from another map is adjusted to tuple!
I would like to hear your opinions!

**Comment by mnishiguchi** [comment]
> In addition, the return value when doing something from another map is adjusted to tuple!

Yeah, I personally like it for the following reasons

- now all the key-value pairs are tuples and it is consistent across the library
- logic is simpler

**Comment by tashirosota** [comment]
@mnishiguchi 
Thanks！

**Pull request merged**
